apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: h5fqo1e0x-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/h5fqo1e0x-dotnet-basic-gitops